### PR TITLE
Fix fortran detection by meson

### PR DESCRIPTION
**Pull request by nicogodet**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nicogodet** [comment]
@conda-forge-admin, please rerender

**Comment by tomsail** [comment]
Thanks @nicogodet for the last PR #22 ! 
Is this PR to remove & simplify some of the patches you've added for the compilation?

**Comment by nicogodet** [comment]
@tomsail The aim here is to fix the build according to https://github.com/conda-forge/compilers-feedstock/issues/70
I don't know why Numpy is not detected with this change...
Out of competence and no time to investigate right now 

#22 now use otm systel.debian.cfg with a patch (I prefer)

**Comment by nicogodet** [comment]
Thanks @isuruf for the fix.
If you have any idea why gfortran is not available, any commit is welcomed !

**Comment by nicogodet** [comment]
This might also be needed at run time

**Pull request merged**
